### ISSUE TITLE
error with power, p == 0

### ISSUE THREAD

**Issue by ajfriend** [ajfriend/cvxpy#1]
I'm starting to get the [power atom](https://github.com/ajfriend/cvxpy/blob/pow/cvxpy/atoms/elementwise/power.py) added, but I get an error
when I run the test script [mytest.py](https://github.com/ajfriend/cvxpy/blob/pow/mytest.py).

The point of the test was to try out the edge case of p=0, which should give an expression of all 1's.
But I get the following error. Any idea what I'm doing wrong, @SteveDiamond?

As a side note, when p=0, so `power(x, 0) == 1`, should the monotonicity of the atom be `u.monotonicity.NONMONOTONIC`?

```
$ ipython mytest.py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/ajfriend/Dropbox/work/cvxpy/mytest.py in <module>()
      7
      8 prob = cvx.Problem(cvx.Maximize(cvx.sum_entries(g) + y), [0 <= x, x <= 1, y <= 2])
----> 9 prob.solve()

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/problem.pyc in solve(self, *args, **kwargs)
    154             return func(self, *args, **kwargs)
    155         else:
--> 156             return self._solve(*args, **kwargs)
    157
    158     @classmethod

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/problem.pyc in _solve(self, solver, ignore_dcp, warm_start, verbose, **kwargs)
    224                 raise Exception("Problem does not follow DCP rules.")
    225
--> 226         objective, constraints = self.canonicalize()
    227         # Choose a solver/check the chosen solver.
    228         if solver is None:

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/problem.pyc in canonicalize(self)
    101         """
    102         canon_constr = []
--> 103         obj, constr = self.objective.canonical_form
    104         canon_constr += constr
    105

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/performance_utils.pyc in _lazyprop(self)
     36         """
     37         if not hasattr(self, attr_name):
---> 38             setattr(self, attr_name, func(self))
     39         return getattr(self, attr_name)
     40     return _lazyprop

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/canonical.pyc in canonical_form(self)
     44             A tuple of (affine expression, [constraints]).
     45         """
---> 46         return self.canonicalize()
     47
     48     @abc.abstractmethod

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/objective.pyc in canonicalize(self)
     82         """Negates the target expression's objective.
     83         """
---> 84         obj, constraints = super(Maximize, self).canonicalize()
     85         return (lu.neg_expr(obj), constraints)
     86

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/objective.pyc in canonicalize(self)
     44         """Pass on the target expression's objective and constraints.
     45         """
---> 46         return self._expr.canonical_form
     47
     48     def variables(self):

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/performance_utils.pyc in _lazyprop(self)
     36         """
     37         if not hasattr(self, attr_name):
---> 38             setattr(self, attr_name, func(self))
     39         return getattr(self, attr_name)
     40     return _lazyprop

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/canonical.pyc in canonical_form(self)
     44             A tuple of (affine expression, [constraints]).
     45         """
---> 46         return self.canonicalize()
     47
     48     @abc.abstractmethod

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/atom.pyc in canonicalize(self)
    114             constraints = []
    115             for arg in self.args:
--> 116                 obj, constr = arg.canonical_form
    117                 arg_objs.append(obj)
    118                 constraints += constr

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/performance_utils.pyc in _lazyprop(self)
     36         """
     37         if not hasattr(self, attr_name):
---> 38             setattr(self, attr_name, func(self))
     39         return getattr(self, attr_name)
     40     return _lazyprop

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/canonical.pyc in canonical_form(self)
     44             A tuple of (affine expression, [constraints]).
     45         """
---> 46         return self.canonicalize()
     47
     48     @abc.abstractmethod

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/atom.pyc in canonicalize(self)
    109             # Non-parameterized expressions are evaluated immediately.
    110             else:
--> 111                 return Constant(self.value).canonical_form
    112         else:
    113             arg_objs = []

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/expressions/constants/constant.pyc in __init__(self, value)
     34             self._sparse = True
     35         else:
---> 36             self._value = intf.DEFAULT_INTERFACE.const_to_matrix(value)
     37             self._sparse = False
     38         # Set DCP attributes.

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/interface/base_matrix_interface.pyc in new_converter(self, value, convert_scalars)
     47     def scalar_const(converter):
     48         def new_converter(self, value, convert_scalars=False):
---> 49             if not convert_scalars and cvxpy.interface.matrix_utilities.is_scalar(value):
     50                 return cvxpy.interface.matrix_utilities.scalar_value(value)
     51             else:

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/interface/matrix_utilities.pyc in is_scalar(constant)
     76 # Is the constant a scalar?
     77 def is_scalar(constant):
---> 78     return size(constant) == (1, 1)
     79
     80 def from_2D_to_1D(constant):

/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/interface/matrix_utilities.pyc in size(constant)
     68         return INTERFACES[sp.csc_matrix].size(constant)
     69     else:
---> 70         raise TypeError("%s is not a valid type for a Constant value." % type(constant))
     71
     72 # Is the constant a column vector?

TypeError: <type 'NoneType'> is not a valid type for a Constant value.
```

**Comment by SteveDiamond** [comment]
In the power atom, you have `one = lu.create_const(1, x.size)`. This only works if `x.size` is (1,1). create_const doesn't promote scalars to vectors. You have to do things like that explicitly, i.e. pass in a vector or matrix of ones.

It doesn't matter what monotonicity you use for constant atoms. Maybe increasing (meaning nondecreasing) would be more correct.

**Comment by ajfriend** [comment]
I tried `one = lu.create_const(np.matrix(np.ones(x.size)), x.size)`
and `one = lu.create_const(np.ones(x.size), x.size)` and neither seemed to work. What should I be writing here?

To understand better, what's the use of the second parameter in `lu.create_const` if the size is just the same as the size of the first parameter?

Also, I'm not sure this is even the problem. `graph_implementation` isn't in the call stack, and if i litter the function with print statements, none of them are being called, so it doesn't seem like `graph_implementation` is even being called before this error message is being printed. Do you have an idea of what's going on?

**Comment by SteveDiamond** [comment]
Ok, I know what's happening. When an atom is constant, it's canonicalized by calling atom.value instead of graph_implementation. 

The reason is that constant atoms can be arbitrary compositions that don't at all follow the DCP rules, e.g. log(square(2) - square(1)). Also, even if the composition is DCP it's better not to create new variables.

But when atom.value is called for your power atom it returns None because it has arguments that have value None (check out the value function in Atom).

Replace Atom.value with this code:

```
    @property
    def value(self):
        # Catch the case when the expression is known to be
        # zero through DCP analysis.
        if self.is_zero():
            result = intf.DEFAULT_INTERFACE.zeros(*self.size)
        else:
            arg_values = []
            for arg in self.args:
                # A argument without a value makes all higher level
                # values None.
                # But if the atom is constant with non-constant
                # arguments it doesn't depend on its arguments,
                # so it isn't None.
                if arg.value is None and not self.is_constant():
                    return None
                else:
                    arg_values.append(arg.value)
            result = self.numeric(arg_values)
        # Reduce to a scalar if possible.
        if intf.size(result) == (1, 1):
            return intf.scalar_value(result)
        else:
            return result
```

You'll need to change power.value so for p=0 it doesn't depend on its argument.

**Comment by ajfriend** [comment]
Cool. Thanks!

So all I did was change `Atom.value()` in `atom.py` as mentioned above and everything seems to work.

I'm not sure how to interpret your last comment, tho. Should I add a `power.value` to `power.py`, or leave it as is with `power` inheriting `value` from `Atom`? Or, is there nothing else that I need to add since everything seems to be working?

**Comment by SteveDiamond** [comment]
By power.value, I meant power.numeric. I had assumed that `np.power(values[0], self.p)` wouldn't work if `values[0]` is None.

**Comment by ajfriend** [comment]
Hmm. It looks like `power.numeric` gets the correct values for `x` when its a numpy array, so I don't think I have to change anything. It looks like `values[0]` is the actual values, not `None`.

**Comment by SteveDiamond** [comment]
values[0] will be None when the argument is a variable. Try doing

x = Variable()
Power(x,0).value

**Comment by ajfriend** [comment]
Ah, I see. I'll fix that.

Another question: This is my current (scalar) implementation for a function that returns the simple weighted geometric mean `t <= sqrt(x*y)`:

```
two = lu.create_const(2, (1, 1))
def gm(t, x, y):
    return SOC(lu.sum_expr([x, y]),
               [lu.sub_expr(x, y),
                lu.mul_expr(two, t, (1, 1))])
```

This method will be used by `power` and `geo_mean`, and p-norms.
Is the correct way to modify this method to handle matrices (i.e. make it elemwise), something like this:

```
def gm(t, x, y):
    size = x.size
    two = lu.create_const(np.mat(2*np.ones(size)), size)
    return SOC(lu.sum_expr([x, y]),
               [lu.sub_expr(x, y),
                lu.mul_expr(two, t, size)])
```

Will that return the correct "elemwise" version of the matrix of constraints?

**Comment by SteveDiamond** [comment]
That's almost correct, but you need to use `SOC_Elemwise` instead of `SOC`.

**Comment by ajfriend** [comment]
OK. I think I have it working. I ended up with this:

```
def gm(t, x, y):
    two = lu.create_const(2, (1, 1))
    return SOC_Elemwise(lu.sum_expr([x, y]),
               [lu.sub_expr(x, y),
                lu.mul_expr(two, t, t.size)])
```

It was initially wrong because I had `lu.create_const(2, t.size)`, so I was a little confused as to why its `(1,1)` instead of `size`. Why is that?

Another thing I was curious about: Why does `lu.mul_expr` need a size parameter if it could conceivably just be exactly the size of either of the parameters? Or does `mul_expr` do something more complicated than elementwise multiplication, like matrix multiplication?

Last question: Even though `power` is an elementwise atom, I would expect that most of the time, users will input scalar arguments. Is there any performance cost to using `SOC_Elemwise`in this case? Should I have an `if` statement to use `SOC` when the arguments are scalar?

**Comment by SteveDiamond** [comment]
`lu.mul_expr` is matrix multiplication and scalar multiplication. There's a different LinOp for elementwise multiplication. Maybe there should be separate LinOps for matrix and scalar multiplication. I'm not sure why I combined those.

It's fine to always use SOC_Elemwise. SOC interprets its arguments in a different way than SOC_Elemwise. It's not much more efficient.

Clearly the whole LinOp and constraint interface is not user friendly. I should redesign it or at least document it.

**Comment by ajfriend** [comment]
More documentation would be great. I'd certainly like to understand the LinOp stuff better. I could definitely help with some kind of developer documentation.
