### ISSUE TITLE
power implementation details

### ISSUE THREAD

**Issue by ajfriend** [ajfriend/cvxpy#2]
I think I've got the power atom completely working, but I've got a few questions for ya, @SteveDiamond.

Since all the functions involving powers need to use something like the geometric mean for their representation, I moved that functionality out to a helper module [power_tools](https://github.com/ajfriend/cvxpy/blob/pow/cvxpy/utilities/power_tools.py). The main helper function there is `gm_constrs`, which forms the internal CVXPY constraints to represent the weighted geometric mean
`t <= x_list[1]^p[1] * x_list[1]^p[1] * ... * x_list[n]^p[n]`,

where `x_list` is a list of `cxvpy.Variable` objects.

Both `geo_mean.py` and `power.py` use this helper function to form their graph implementation.
1. I'm passing in a python list of cvxpy.Variables to `gm_constrs`. For `geo_mean`, I form
   `x_list = [index.get_index(arg_objs[0], [], i, 0) for i in range(len(w))]` before calling `gm_constrs(t, x_list, w)`, since I'm expecting `x` to be a vector. For `power.py` I do something a [little different](https://github.com/ajfriend/cvxpy/blob/pow/cvxpy/atoms/elementwise/power.py#L133), as I'm expecting only a 'single' (but elemwise) x. Is forming a list as I currently do it the best approach? Or should I be using some CVXPY construct?
2. `geo_mean` and `power` each use the same helper function. But one is elemwise and the other isn't. Since geo_mean isn't elemwise, my original code used `SOC` to form the constraints. Since the helper function now supports both, I use `SOC_Elemwise`. Does that cost us anything in the geo_mean case? If it doesn't cost much, would it make sense to consolidate SOC and SOC_Elemwise into a single, general function? Put another way, is it always OK to just use `SOC_Elemwise`?

**Comment by SteveDiamond** [comment]
Forming a list is fine. I guess it will be slower than doing everything elementwise if someone does geo_mean on a vector of length 1 million, but that's pretty unlikely.

SOC_Elemwise and SOC interpret their inputs differently. They are only equivalent if all arguments are scalars. SOC_Elemwise takes a t vector/matrix and a list of x vectors/matrices and makes an SOC constraint for each element in the t vector/matrix and the corresponding entries of the x vectors/matrices.

SOC takes a t scalar and a list of x vectors/matrices and makes a single SOC constraint where all the x vectors/matrices are vectorized and combined.

So if I write SOC(t, [x1, x2]) it creates the constraint ||(x1, x2)||_2 <= t, whereas 
SOC_Elemwise(t, [x1, x2]) creates the constraints ||(x1[i], x2[i])||_2 <= t[i] for every entry in t.

**Comment by ajfriend** [comment]
OK, so it should be alright to use SOC_Elemwise in the helper function for
geo_mean, even though geo_mean isn't elemwise? If I'm understanding
correctly, in the specific way I'm using them for geo_mean, the two are
functionally equivalent.

**Comment by SteveDiamond** [comment]
Yes, they're the same if all the arguments are scalars.
